jobs:
  - job: build
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - task: PowerShell@2
        displayName: 'Setup Dynamo'
        inputs:
          targetType: inline
          workingDirectory: $(System.DefaultWorkingDirectory)
          script: |
            iwr -outf dynamo.zip https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.zip
            mkdir dynamo
            Expand-Archive -Path dynamo.zip -DestinationPath dynamo
            cd dynamo
            javaw -D"java.library.path=./DynamoDBLocal_lib" -jar DynamoDBLocal.jar
      - task: PowerShell@2
        displayName: 'Setup Consul'
        inputs:
          targetType: inline
          workingDirectory: $(System.DefaultWorkingDirectory)
          script: |
            iwr -outf consul.zip https://releases.hashicorp.com/consul/1.4.2/consul_1.4.2_windows_amd64.zip
            mkdir consul
            Expand-Archive -Path consul.zip -DestinationPath consul
            cd consul
            sc.exe create "Consul" binPath="$(System.DefaultWorkingDirectory)/consul/consul.exe agent -dev"
            sc.exe start "Consul"
      - task: PowerShell@2
        displayName: 'Setup Redis'
        inputs:
          targetType: inline
          workingDirectory: $(System.DefaultWorkingDirectory)
          script: |
            iwr -outf redis.zip https://github.com/MicrosoftArchive/redis/releases/download/win-3.0.504/Redis-x64-3.0.504.zip
            mkdir redis
            Expand-Archive -Path redis.zip -DestinationPath redis
            cd redis
            ./redis-server --service-install
            ./redis-server --service-start
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '2.7'
          addToPath: true
      - task: PowerShell@2
        displayName: 'Setup SDK and Test 2.7'
        inputs:
          targetType: inline
          workingDirectory: $(System.DefaultWorkingDirectory)
          script: |
            python --version
            pip install -r test-requirements.txt
            pip install -r consul-requirements.txt
            python setup.py install
            mkdir test-reports27
            python -m pytest -s --junitxml=test-reports27/junit.xml testing;
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.7'
          addToPath: true
      - task: PowerShell@2
        displayName: 'Setup SDK and Test 3.7'
        inputs:
          targetType: inline
          workingDirectory: $(System.DefaultWorkingDirectory)
          script: |
            python --version
            pip install -r test-requirements.txt
            pip install -r consul-requirements.txt
            python setup.py install
            mkdir test-reports37
            python -m pytest -s --junitxml=test-reports37/junit.xml testing;
